#!/bin/bash

restore=$PWD
cd ~

# Get a nice .vimrc file

curl -Ss http://git.io/AimPxw > .vimrc

# Create a nice .vim directory

mkdir -p ~/.vim
mkdir -p ~/.vim/undo
mkdir -p ~/.vim/backups

# Get pathogen

mkdir -p ~/.vim/autoload ~/.vim/bundle; \
curl -Sso ~/.vim/autoload/pathogen.vim http://git.io/PJdY8Q

# Get some bundles

cd ~/.vim/bundle

# Get synatastic

curl -SsL http://git.io/syntastic > syntastic.tar.gz
tar -xzf syntastic.tar.gz
rm syntastic.tar.gz

# Get vim-javascript

curl -SsL http://git.io/vim-javscript > vim-javascript.tar.gz
tar -xzf vim-javascript.tar.gz
rm vim-javascript.tar.gz

# Get vim-trailing-whitespaces

curl -SsL http://git.io/vim-trailing-whitespace > vim-trailing-whitespace.tar.gz
tar -xzf vim-trailing-whitespace.tar.gz
rm vim-trailing-whitespace.tar.gz

cd $restore
